#!/usr/bin/php
<?php
/*
Copyright 2014-2019 Ondrej Novy

This file is part of otodo.

otodo is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

otodo is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with otodo.  If not, see <http://www.gnu.org/licenses/>.
*/

require_once dirname(__FILE__) . '/init.php';

$configFile = null;
if ($argc == 2) {
	$configFile = $argv[1];
} else {
	$configFile = dirname(__FILE__) . '/config.ini';
}
try {
	Config::loadFile($configFile);
} catch (ConfigLoadException $cle) {
	echo $cle->getMessage() . PHP_EOL;
	exit(-1);
}

$g = new Gui();
$g->start();
